# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='lid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='wlid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordstatus',
            name='lid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordstatus',
            name='wlid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
