# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanat', '0002_auto_20160228_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordstatus',
            name='c_long',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wordstatus',
            name='c_med',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wordstatus',
            name='c_short',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wordstatus',
            name='last_c_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordstatus',
            name='last_c_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordstatus',
            name='last_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
