# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanat', '0003_auto_20160228_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordstatus',
            name='ask_at_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wordstatus',
            name='ask_at_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
