# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanat', '0005_wordstatus_last_streak'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='wordstatus',
            index_together=set([('last_seq',), ('lid', 'wlid')]),
        ),
    ]
